version: '3.9'

services:
  db:
    image: techmaps-db-image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

  app:
    image: techmaps-app-image
    depends_on:
      - db
    environment:
      SECRET_KEY_FILE: /run/secrets/secret_key
    secrets:
      - secret_key
    ports:
      - "8757:8757"

secrets:
  secret_key:
    external: true

volumes:
    pgdata:

networks:
  default:
    driver: overlay