security:
  jwt:
    secretKey: ${secret}
    tokenPrefix: 'Bearer '
    tokenExpirationAfterMinutes: 30
    refreshTokenExpirationAfterDays: 14

server:
  port: 8757
  error:
    include-message: always

spring:
  application:
    name: techmaps-v2
  datasource:
    url: jdbc:postgresql://localhost:5432/techmaps
    username: techmaps-app
    password: techmaps-app
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

queries:
  sql:
    user-dao:
      insert:
        user: >
          INSERT INTO techmaps_platform.user (id, email, username, password) 
          VALUES (?, ?, ?, ?)
      select:
        user-by-id: >
          SELECT * FROM techmaps_platform.user WHERE id = ?
        user-by-email: >
          SELECT * FROM techmaps_platform.user WHERE email = ?
        user-by-username: >
          SELECT * FROM techmaps_platform.user WHERE username = ?
          user-by-id: >
          SELECT * FROM techmaps_platform.user WHERE id = ?
      update:
        user: >
          UPDATE techmaps_platform.user SET email = ?, username = ?, password = ? WHERE id = ?
      exists:
        user-by-id: >
          SELECT EXISTS(SELECT 1 FROM techmaps_platform.user WHERE id = ?)
    dashboard-dao:
      insert:
        dashboard: >
          INSERT INTO techmaps_platform.dashboard (id, user_id, total_roadmaps)
          VALUES (?, ?, ?)
      select:
        dashboard-by-id: >
          SELECT * FROM techmaps_platform.dashboard WHERE id = ?
        dashboard-by-user-id: >
          SELECT * FROM techmaps_platform.dashboard WHERE user_id = ?
      exists:
        dashboard-by-id: >
          SELECT EXISTS(SELECT 1 FROM techmaps_platform.dashboard WHERE id = ?)
    roadmap-dao:
      insert:
        roadmap: >
          INSERT INTO techmaps_platform.roadmap (id, name, language)
          VALUES (?, ?, ?::techmaps_platform.language)
      select:
        roadmap-by-id: >
          SELECT * FROM techmaps_platform.roadmap WHERE id = ?
        roadmap-by-name: >
          SELECT * FROM techmaps_platform.roadmap WHERE name = ?
      update:
        roadmap: >
          UPDATE techmaps_platform.roadmap SET name = ?, language = ?::techmaps_platform.language WHERE id = ?
      exists:
        roadmap-by-id: >
          SELECT EXISTS(SELECT 1 FROM techmaps_platform.roadmap WHERE id = ?)
    school-dao:
      insert:
        school: >
          INSERT INTO techmaps_platform.school (id, name) VALUES (?, ?)
      select:
        school-by-id: >
          SELECT * FROM techmaps_platform.school WHERE id = ?
        school-by-name: >
          SELECT * FROM techmaps_platform.school WHERE name = ?
      update:
          school: >
              UPDATE techmaps_platform.school SET name = ? WHERE id = ?
      exists:
        school-by-id: >
          SELECT EXISTS(SELECT 1 FROM techmaps_platform.school WHERE id = ?)