security:
  jwt:
    secretKey: ${secret:theItsyBitsySpiderClimbedUpTheWaterspoutDownCameTheRainAndWashedTheSpiderOutTheSunCameOutAndDriedUpAllTheRainAndTheItsyBitsySpiderClimbedUpTheSpoutAgain}
    tokenPrefix: 'Bearer '
    tokenExpirationAfterMinutes: 30
    refreshTokenExpirationAfterDays: 14

server:
  port: 8757
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: techmaps-v2
  datasource:
    url: jdbc:postgresql://localhost:5432/techmaps
    username: techmaps-app
    password: techmaps-app
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

queries:
  sql:
    user-dao:
      insert:
        user: >
          INSERT INTO techmaps_platform.user (id, email, username, password) 
          VALUES (?, ?, ?, ?)
      select:
        user-by-id: >
          SELECT * FROM techmaps_platform.user WHERE id = ?
        user-by-email: >
          SELECT * FROM techmaps_platform.user WHERE email = ?
        user-by-username: >
          SELECT * FROM techmaps_platform.user WHERE username = ?
          user-by-id: >
          SELECT * FROM techmaps_platform.user WHERE id = ?
      update:
        user: >
          UPDATE techmaps_platform.user SET email = ?, username = ?, password = ? WHERE id = ?
      exists:
        user-by-id: >
          SELECT EXISTS(SELECT 1 FROM techmaps_platform.user WHERE id = ?)
    dashboard-dao:
      insert:
        dashboard: >
          INSERT INTO techmaps_platform.dashboard (id, user_id, total_roadmaps)
          VALUES (?, ?, ?)
      select:
        dashboard-by-id: >
          SELECT * FROM techmaps_platform.dashboard WHERE id = ?
        dashboard-by-user-id: >
          SELECT * FROM techmaps_platform.dashboard WHERE user_id = ?
      exists:
        dashboard-by-id: >
          SELECT EXISTS(SELECT 1 FROM techmaps_platform.dashboard WHERE id = ?)
    roadmap-dao:
      insert:
        roadmap: >
          INSERT INTO techmaps_platform.roadmap (id, name, language)
          VALUES (?, ?, ?::techmaps_platform.language)
      select:
        roadmap-by-id: >
          SELECT * FROM techmaps_platform.roadmap WHERE id = ?
        roadmap-by-name: >
          SELECT * FROM techmaps_platform.roadmap WHERE name = ?
      update:
        roadmap: >
          UPDATE techmaps_platform.roadmap SET name = ?, language = ?::techmaps_platform.language WHERE id = ?
      exists:
        roadmap-by-id: >
          SELECT EXISTS(SELECT 1 FROM techmaps_platform.roadmap WHERE id = ?)
    roadmap-user-dao:
      insert:
        roadmap-user: >
          INSERT INTO techmaps_platform.roadmap_user (id, roadmap_id, user_id, is_done, start_time) VALUES (?, ?, ?, ?, ?)
      select:
        roadmap-user-by-id: >
          SELECT * FROM techmaps_platform.roadmap_user WHERE id = ?
        roadmap-user-by-roadmap-id: >
          SELECT * FROM techmaps_platform.roadmap_user WHERE roadmap_id = ?
        roadmap-user-by-user-id: >
          SELECT * FROM techmaps_platform.roadmap_user WHERE user_id = ?
      update:
        roadmap-user-is-done: >
          UPDATE techmaps_platform.roadmap_user SET is_done = ? WHERE id = ?
        roadmap-user-end-time: >
          UPDATE techmaps_platform.roadmap_user SET end_time = ? WHERE id = ?
      delete:
        roadmap-user: >
          DELETE FROM techmaps_platform.roadmap_user WHERE id = ?
    group-dao:
      insert:
        group: >
          INSERT INTO techmaps_platform.group (id, name, parent_id) VALUES (?, ?, ?)
      select:
        group-by-id: >
          SELECT * FROM techmaps_platform.group WHERE id = ?
        group-by-name: >
          SELECT * FROM techmaps_platform.group WHERE name = ?
        group-by-parent-id: >
          SELECT * FROM techmaps_platform.group WHERE parent_id = ?
        group-hierarchy-by-group-id: >
          WITH RECURSIVE group_tree AS (
            SELECT id, name, parent_id
            FROM techmaps_platform.group
            WHERE id = ?
            UNION
            SELECT g.id, g.name, g.parent_id
            FROM techmaps_platform.group g
            JOIN group_tree gt ON g.id = gt.parent_id
          )
          SELECT * FROM group_tree
      update:
          group: >
              UPDATE techmaps_platform.group SET name = ?, parent_id = ? WHERE id = ?
      exists:
        group-by-id: >
          SELECT EXISTS(SELECT 1 FROM techmaps_platform.group WHERE id = ?)
    group-user-dao:
      insert:
        group-user: >
          INSERT INTO techmaps_platform.group_user (id, group_id, user_id, role)
            VALUES (?, ?, ?, ?::techmaps_platform.role)
      select:
        group-user-by-id: >
          SELECT * FROM techmaps_platform.group_user WHERE id = ?
        group-user-by-group-id: >
          SELECT * FROM techmaps_platform.group_user WHERE group_id = ?
        group-user-by-user-id: >
          SELECT * FROM techmaps_platform.group_user WHERE user_id = ?
      update:
        role: >
          UPDATE techmaps_platform.group_user SET role = ?::techmaps_platform.role WHERE id = ?
      delete:
        group-user: >
          DELETE FROM techmaps_platform.group_user WHERE id = ?
      exists:
        group-user-by-id: >
          SELECT EXISTS(SELECT 1 FROM techmaps_platform.group_user WHERE id = ?)
    group-roadmap-dao:
      insert:
        group-roadmap: >
          INSERT INTO techmaps_platform.group_roadmap (id, group_id, roadmap_id) VALUES (?, ?, ?)
      select:
        group-roadmap-by-id: >
          SELECT * FROM techmaps_platform.group_roadmap WHERE id = ?
        group-roadmap-by-group-id: >
          SELECT * FROM techmaps_platform.group_roadmap WHERE group_id = ?
        group-roadmap-by-roadmap-id: >
          SELECT * FROM techmaps_platform.group_roadmap WHERE roadmap_id = ?
      delete:
        group-roadmap: >
          DELETE FROM techmaps_platform.group_roadmap WHERE id = ?
      exists:
        group-roadmap-by-id: >
          SELECT EXISTS(SELECT 1 FROM techmaps_platform.group_roadmap WHERE id = ?)
    stage-dao:
      insert:
        stage: >
          INSERT INTO techmaps_platform.stage (id, roadmap_id, name, position) VALUES (?, ?, ?, ?)
      select:
        stage-by-id: >
          SELECT * FROM techmaps_platform.stage WHERE id = ?
        stage-by-roadmap-id: >
          SELECT * FROM techmaps_platform.stage WHERE roadmap_id = ?
      update:
        name: >
          UPDATE techmaps_platform.stage SET name = ?, position = ? WHERE id = ?
      delete:
        stage: >
          DELETE FROM techmaps_platform.stage WHERE id = ?
      exists:
        stage-by-id: >
          SELECT EXISTS(SELECT 1 FROM techmaps_platform.stage WHERE id = ?)
    stage-user-dao:
      insert:
        stage-user: >
          INSERT INTO techmaps_platform.stage_user (id, stage_id, roadmap_user_id, is_done, position) VALUES (?, ?, ?, ?, ?)
      select:
        stage-user-by-id: >
          SELECT * FROM techmaps_platform.stage_user WHERE id = ?
        stage-user-by-stage-id: >
          SELECT * FROM techmaps_platform.stage_user WHERE stage_id = ?
        stage-user-by-roadmap-user-id: >
          SELECT * FROM techmaps_platform.stage_user WHERE roadmap_user_id = ?
      update:
        stage-user: >
          UPDATE techmaps_platform.stage_user SET is_done = ?, position = ? WHERE id = ?
      delete:
        stage-user: >
          DELETE FROM techmaps_platform.stage_user WHERE id = ?
    task-dao:
      insert:
        task: >
          INSERT INTO techmaps_platform.task (id, stage_id, title, description, position) VALUES (?, ?, ?, ?, ?)
      select:
        task-by-id: >
          SELECT * FROM techmaps_platform.task WHERE id = ?
        task-by-stage-id: >
          SELECT * FROM techmaps_platform.task WHERE stage_id = ?
      update:
        task: >
          UPDATE techmaps_platform.task SET title = ?, description = ?, position = ? WHERE id = ?
      delete:
        task: >
          DELETE FROM techmaps_platform.task WHERE id = ?
    task-user-dao:
      insert:
        task-user: >
          INSERT INTO techmaps_platform.task_user (id, task_id, roadmap_user_id, is_done) VALUES (?, ?, ?, ?)
      select:
        task-user-by-id: >
          SELECT * FROM techmaps_platform.task_user WHERE id = ?
        task-user-by-task-id: >
          SELECT * FROM techmaps_platform.task_user WHERE task_id = ?
        task-user-by-roadmap-user-id: >
          SELECT * FROM techmaps_platform.task_user WHERE roadmap_user_id = ?
      update:
        task-user-is-done: >
          UPDATE techmaps_platform.task_user SET is_done = ? WHERE id = ?
      delete:
        task-user: >
          DELETE FROM techmaps_platform.task_user WHERE id = ?
    step-dao:
      insert:
        step: >
          INSERT INTO techmaps_platform.step (id, task_id, position, text, link) VALUES (?, ?, ?, ?, ?)
      select:
        step-by-id: >
          SELECT * FROM techmaps_platform.step WHERE id = ?
        step-by-task-id: >
          SELECT * FROM techmaps_platform.step WHERE task_id = ?
      update:
        step: >
          UPDATE techmaps_platform.step SET position = ?, text = ?, link = ? WHERE id = ?
      delete:
        step: >
          DELETE FROM techmaps_platform.step WHERE id = ?
    step-user-dao:
      insert: >
        INSERT INTO techmaps_platform.step_user (id, step_id, roadmap_user_id, is_done) VALUES (?, ?, ?, ?)
      select:
        by-id: >
          SELECT * FROM techmaps_platform.step_user WHERE id = ?
        by-step-id: >
          SELECT * FROM techmaps_platform.step_user WHERE step_id = ?
        by-roadmap-user-id: >
          SELECT * FROM techmaps_platform.step_user WHERE roadmap_user_id = ?
      update:
        status: >
          UPDATE techmaps_platform.step_user SET is_done = ? WHERE id = ?
      delete: >
        DELETE FROM techmaps_platform.step_user WHERE id = ?