name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run PostgreSQL migrations
      env:
        PGPASSWORD: postgres
      run: |
        for file in docker/postgres/*
        do
          if [[ "$file" =~ V000 ]]; then
            psql -h localhost -U postgres postgres -f "$file"
          else
            psql -h localhost -U postgres techmaps -f "$file"
          fi
        done
    - name: Build with Maven
      run: mvn -B package --file pom.xml
